### ISSUE TITLE
cleanupAvalaraJobs moment require fails

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#3757]
Uncaught exception in `cleanupAvalaraJobs`.  Most likely introduced in #3602 / #2635
### Expected behavior
No errors.

### Actual behavior
```
Exception in setTimeout callback: TypeError: moment is not a function
    at cleanupAvalaraJobs (imports/plugins/included/taxes-avalara/server/jobs/cleanup.js:24:23)
    at JobQueue.Jobs.processJobs [as worker] (imports/plugins/included/taxes-avalara/server/jobs/cleanup.js:62:7)
    at JobQueue._process (packages/vsivsi_job-collection/job/src/job_class.coffee:191:8)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at packages/meteor.js:502:25
    at runWithEnvironment (packages/meteor.js:1240:24)
```
### Steps to reproduce the behavior

Enable avalara, wait for job to run, or run the job manually.

### Versions
Node: 8.9.3
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: refactor-3600-spencern-upgrade-meteor-1.6.1
Docker: 17.12.0-ce

**Comment by prinzdezibel** [comment]
This issue is fixed via: PR https://github.com/reactioncommerce/reaction/pull/3780

**Comment by prinzdezibel** [comment]
PR 3780 was merged in. closing.
