### ISSUE TITLE
Uncaught client error in fulfilling orders

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1202]
### Expected behavior

No console errors.

### Actual Behavior
Uncaught Error in console

```
Exception in template helper: TypeError: iterator.call is not a function
    at http://localhost:3000/packages/underscore.js?hash=27b3d669b418de8577518760446467e6ff429b1e:228:20
    at Array.some (native)
    at _.some._.any (http://localhost:3000/packages/underscore.js?hash=27b3d669b418de8577518760446467e6ff429b1e:277:59)
    at Function._.find._.detect (http://localhost:3000/packages/underscore.js?hash=27b3d669b418de8577518760446467e6ff429b1e:227:5)
    at http://localhost:3000/app/app.js?hash=1d1efd96a6ebe4f986275c30cbc450fd860696b8:20874:30
    at Array.map (native)
    at Function._.map._.collect (http://localhost:3000/packages/underscore.js?hash=27b3d669b418de8577518760446467e6ff429b1e:167:56)
    at Object.items (http://localhost:3000/app/app.js?hash=1d1efd96a6ebe4f986275c30cbc450fd860696b8:20873:21)
    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2994:16
    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1653:16
```
### Steps to Reproduce the Behavior

Place order using example payment method. Click Start in admin order dashboard. Observe console.

**Comment by aaronjudd** [comment]
Introduced in #1136, resolved in #1203.

**Comment by zenweasel** [comment]
So it was introduced in a PR that hasn't been merged and resolved in a PR that hasn't been merged?
